name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  flutter-test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Dart (explicitly specify Dart version)
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          channel: stable
          version: 3.2.0 # Explicitly set Dart version

      # Step 3: Set up Flutter (use a specific version)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Use a specific version of Flutter

      # Step 4: Precache Dependencies
      - name: Flutter Precache
        run: flutter precache

      # Step 5: Run Flutter Doctor (Optional, for Debugging)
      - name: Flutter Doctor
        run: flutter doctor

      # Step 6: Run Tests
      - name: Run Tests
        run: flutter test

      # Step 7: Cache dependencies
      - name: Cache Pub Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
